### PR TITLE
[DRAFT] Refactor auth calls 

### PR DESCRIPTION
**Pull request by alex-hall**
!!This PR is very much a WIP!!

This PR attempts to refactor the main.ts class into two discreet classes: 

`main.ts`, which only contains public API methods and some smaller methods to support those public methods:
- getDailyData
- getMonthlyData
- getHourlyData
- getAllBillsData
- fetchServicePointNumber

`Helper.ts` Contains all of the authentication methods and supporting methods: 
- fetchJwt
- login
- getAccountsAray
- getAccounts
- getRequestVerificationToken
- getScWebToken

And additionally contains a public helper to handle the auth headers for calling the API and deserializing JSON. 
- makeApiRequest

It temporarily supports a public `getJwt` method because there are other API calls in main.ts that rely on the Jwt that don't play nice with the existing `makeApiRequest` method. Same goes for `getAccountsArray`

Remaining work: 
- Make sense of `login` method, separate out the JWT calls from the account calls
- Figure out who all is reliant on the account calls and replace those references

### CODE REVIEW

**Comment by harrisonhjones** [comment]
Can you make this PR reference #27 instead of master so it's more clear what's changing?

**Comment by alex-hall** [comment]
> Can you make this PR reference #27 instead of master so it's more clear what's changing?

Seems like [this isn't possible](https://stackoverflow.com/questions/26619478/are-dependent-pull-requests-in-github-possible) since my branch doesn't exist on this repo. Hopefully since the other PR is approved it'll get merged soon.

**Comment by harrisonhjones** [comment]
@alex-hall looks like everything has been merged; you just need to refactor?

Also: where do you want to continue the HASS integration discussion? Seems a bit tangential to do it here.

**Comment by alex-hall** [comment]
> @alex-hall looks like everything has been merged; you just need to refactor?
> 
> Also: where do you want to continue the HASS integration discussion? Seems a bit tangential to do it here.
 
 honestly this work is a bit lower priority for me and the HASS stuff is higher priority.

want to join the home assistant discord? https://www.home-assistant.io/help/

**Comment by harrisonhjones** [comment]
> want to join the home assistant discord? https://www.home-assistant.io/help/

Done; which channel do you want to use in there to discuss?

**Comment by alex-hall** [comment]
> > want to join the home assistant discord? https://www.home-assistant.io/help/
> 
> Done; which channel do you want to use in there to discuss?

I posted in dev_addons

**Pull request closed without merging**
